name: pygbag_build
on: [workflow_dispatch]

jobs:
  build-pygbag:
    name: Build for Emscripten pygbag runtime
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install pygbag
      run: |
        python -m pip install pygbag

    - name: Build with pygbag
      working-directory: ./src
      run: |
        python -m pygbag --build .

    - name: Upload to GitHub Pages branch gh-pages
      uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
        branch: gh-pages
        folder: src/build/web
